### ISSUE TITLE
Study Material UI Required

### ISSUE THREAD

**Issue by priyanshnama** [BitByte-TPC/Jagrati#1]
add this UI to the app.
the screen it to be added to study material fragemnt and next one in a new activity and then connect the both.

![image](https://user-images.githubusercontent.com/54625644/94989094-cfd16180-058f-11eb-95c4-138023593dd9.png)

**Comment by akshatgondane** [comment]
Assign this to me

**Comment by priyanshnama** [comment]
go ahead @akshatgondane

**Comment by priyanshnama** [comment]
@akshatgondane 
Comment down here before opening a pull request as we are currently facing some problem regarding GitHub actions
